[package]
name = "beta"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
aes-gcm = "0.10.3"
rand = "0.9.2"
base64 = "0.22.1"

